In [1]:
import torch
import matplotlib.pyplot as plt
import random
import math
from torch.autograd import Variable
import pandas as pd
import numpy as np

In [2]:
import matplotlib
matplotlib.rcParams['figure.figsize'] = (13.0, 5.0)
%matplotlib inline

In [3]:
torch.cuda.is_available()

True

In [4]:
def myFunction(x, y):
    return math.sin(x + 2*y)*math.exp(-  pow((2*x + y), 2))

In [5]:
def randomDif():
    x = random.randrange(0, 1000)/100
    y = random.randint(0, 1)
    if y==1:
        return x
    else:
        return x*-1

In [6]:
dataset_array = []

In [7]:
number = 0
while number < 20000:
    x = randomDif()
    y = randomDif()
    z = myFunction(x, y)
    dataset_array.append([x, y, z])
    number += 1

In [8]:
dataframe = pd.DataFrame(dataset_array)

In [9]:
dataframe.head(3)

0     1              2
0  2.01  2.38   7.609749e-19
1 -6.37  3.38   3.401207e-39
2  9.07  5.74  2.177713e-248

In [10]:
train_df = dataframe.iloc [:13999]
test_df = dataframe.iloc [14000:16999]
val_df = dataframe.iloc [17000:]

In [11]:
y_train = torch.tensor(train_df[2].values)
y_validation = torch.tensor(test_df[2].values)
y_test = torch.tensor(val_df[2].values)

In [12]:
train_df = train_df.drop(train_df.columns[[2]], axis=1) 
test_df = test_df.drop(test_df.columns[[2]], axis=1) 
val_df = val_df.drop(val_df.columns[[2]], axis=1) 

In [13]:
x_train = torch.tensor(train_df.values)
x_validation = torch.tensor(val_df.values)
x_test = torch.tensor(test_df.values)

In [14]:
display(x_train) 

tensor([[ 2.0100,  2.3800],
        [-6.3700,  3.3800],
        [ 9.0700,  5.7400],
        ...,
        [-9.2400,  0.1900],
        [ 0.5400, -0.8100],
        [-3.2400,  3.2200]], dtype=torch.float64)

In [15]:
display(y_train) 

tensor([  7.6097e-19,   3.4012e-39,  2.1777e-248,  ..., -2.7962e-146,
         -8.1995e-01,  -1.4149e-06], dtype=torch.float64)

In [16]:
display(x_validation) 

tensor([[ 4.9200,  9.7400],
        [ 1.0000, -9.5800],
        [ 4.9600,  9.9600],
        ...,
        [ 9.8200, -7.5100],
        [ 8.1400, -8.7100],
        [-0.1000,  1.4300]], dtype=torch.float64)

In [17]:
display(y_validation) 

tensor([ 3.0104e-06, 8.0025e-109, 1.4749e-100,  ..., -2.0220e-01,
        3.8038e-191,  5.9620e-09], dtype=torch.float64)

In [18]:
display(x_test) 

tensor([[ 6.3300, -9.2000],
        [-6.6400, -2.4900],
        [-6.5400, -2.0800],
        ...,
        [ 4.2500, -8.5100],
        [ 6.8700,  7.1900],
        [ 0.5800, -5.4900]], dtype=torch.float64)

In [19]:
display(y_test) 

tensor([-2.1238e-167,   7.0891e-26, -5.7360e-173,  ...,   1.1103e-64,
         -1.8706e-26,   8.2028e-02], dtype=torch.float64)

In [20]:
x_train = x_train.to(torch.float)
x_validation = x_validation.to(torch.float)
x_test = x_test.to(torch.float)
y_train = y_train.to(torch.float)
y_validation = y_validation.to(torch.float)
y_test = y_test.to(torch.float)

In [21]:
display(x_train) 

tensor([[ 2.0100,  2.3800],
        [-6.3700,  3.3800],
        [ 9.0700,  5.7400],
        ...,
        [-9.2400,  0.1900],
        [ 0.5400, -0.8100],
        [-3.2400,  3.2200]])

In [22]:
class NeuroeNet(torch.nn.Module):
    def __init__(self, n_hidden_neurons):
        super(NeuroeNet, self).__init__()
        self.fc1 = torch.nn.Linear(1, n_hidden_neurons)
        self.act1 = torch.nn.Sigmoid()
        self.fc2 = torch.nn.Linear(n_hidden_neurons, 1)

    def forward(self, x):
        x = self.fc1(x)
        x = self.act1(x)
        x = self.fc2(x)
        return x

neuro_net = NeuroeNet(3)

In [23]:
def predict(net, x, y):
    y_pred = net.forward(x)

In [24]:
predict(neuro_net, x_validation, y_validation)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3000x2 and 1x3)